apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dr-demo-primary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bhanu0710/multi-region-gitops-dr.git
    targetRevision: main
    path: helm/dr-demo
    helm:
      parameters:
        - name: clusterRole
          value: primary
        - name: awsRegion
          value: ap-south-1
        - name: ingress.host
          value: primary.dr-demo.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: dr-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
